"""Build a self-contained HTML experiment report from evaluation JSON files."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path


def _pct(value: float | None) -> str:
    return "—" if value is None else f"{100 * value:.1f}%"


def _bar(value: float, color: str = "#33d6a6") -> str:
    width = max(0.0, min(100.0, value * 100))
    return f'<div class="bar"><i style="width:{width:.2f}%;background:{color}"></i></div>'


def build_report(results: list[dict], title: str) -> str:
    columns = []
    for result in results:
        metrics = result["metrics"]
        name = html.escape(Path(result["model"]).name)
        columns.append(
            f"""
            <article class="card">
              <h3>{name}</h3>
              <div class="score">{_pct(metrics['strict_accuracy'])}</div>
              <div class="label">strict accuracy</div>
              <p>Valid expressions {_pct(metrics['parseable_rate'])}</p>
              {_bar(metrics['parseable_rate'])}
              <p>Exact number use {_pct(metrics['exact_number_usage_rate'])}</p>
              {_bar(metrics['exact_number_usage_rate'], '#7aa2ff')}
            </article>"""
        )
    rows = []
    metric_names = [
        ("strict_accuracy", "Strict accuracy"),
        ("parseable_rate", "Parseable expression"),
        ("exact_number_usage_rate", "Exact number usage"),
        ("format_rate", "Format compliance"),
    ]
    for key, label in metric_names:
        cells = "".join(f"<td>{_pct(r['metrics'].get(key))}</td>" for r in results)
        rows.append(f"<tr><th>{label}</th>{cells}</tr>")
    headers = "".join(f"<th>{html.escape(Path(r['model']).name)}</th>" for r in results)
    failure_blocks = []
    for result in results:
        failures = result["metrics"].get("failure_taxonomy", {})
        total = max(1, sum(failures.values()))
        items = "".join(
            f"<li><span>{html.escape(name)}</span><b>{count}</b>{_bar(count / total, '#ffb86b')}</li>"
            for name, count in sorted(failures.items(), key=lambda item: -item[1])
        )
        failure_blocks.append(
            f"<article class='card'><h3>{html.escape(Path(result['model']).name)}</h3>"
            f"<ul>{items}</ul></article>"
        )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>{html.escape(title)}</title><style>
:root{{--bg:#09111f;--panel:#111d31;--text:#edf4ff;--muted:#9aacbf;--line:#263854}}
*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at top,#172846,var(--bg) 55%);
color:var(--text);font:15px/1.55 system-ui,sans-serif}}main{{max-width:1100px;margin:auto;padding:64px 24px}}
h1{{font-size:clamp(2rem,5vw,4rem);line-height:1;margin:.2em 0}}h2{{margin-top:48px}}p.sub{{color:var(--muted);max-width:720px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}}.card{{background:rgba(17,29,49,.88);
border:1px solid var(--line);border-radius:16px;padding:22px;box-shadow:0 12px 40px #0004}}.score{{font-size:3rem;font-weight:750}}
.label{{color:var(--muted);margin-top:-8px}}.bar{{height:7px;background:#23334b;border-radius:9px;overflow:hidden}}.bar i{{display:block;height:100%}}
table{{width:100%;border-collapse:collapse;background:var(--panel);border-radius:14px;overflow:hidden}}th,td{{padding:14px;border-bottom:1px solid var(--line);text-align:right}}th:first-child{{text-align:left}}ul{{list-style:none;padding:0}}li{{margin:14px 0}}li b{{float:right}}
footer{{margin-top:48px;color:var(--muted)}}code{{color:#9ee6cf}}</style></head>
<body><main><p>MANISH AI FASTPATH LABS · RESEARCH ARTIFACT</p><h1>{html.escape(title)}</h1>
<p class="sub">Zero-SFT GRPO on Countdown, measured with a strict symbolic verifier and
combination-disjoint evaluation. This report contains measured results only.</p>
<section class="grid">{''.join(columns)}</section><h2>Comparison</h2>
<table><thead><tr><th>Metric</th>{headers}</tr></thead><tbody>{''.join(rows)}</tbody></table>
<h2>Failure taxonomy</h2><section class="grid">{''.join(failure_blocks)}</section>
<footer>Generated by <code>countdown-report</code>. Inspect the source JSON for every completion.</footer>
</main></body></html>"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("results", nargs="+")
    parser.add_argument("--title", default="Verifiable RL from Base")
    parser.add_argument("--output", default="reports/index.html")
    args = parser.parse_args()
    results = [json.loads(Path(path).read_text()) for path in args.results]
    destination = Path(args.output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(build_report(results, args.title))
    print(destination)


if __name__ == "__main__":
    main()

